name: ✨ Feature Request
description: Suggest an enhancement or new capability.
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve WatchForge! Please provide enough context so we can evaluate and implement.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem are you trying to solve?
      placeholder: "As a user, I want..., because..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see built?
      placeholder: "Build/Change..., include..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you’ve considered?
      placeholder: "Alternative A..., Alternative B..."
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / Notes
      description: UX notes, API ideas, data model thoughts, edge cases, etc.
      placeholder: "Notes..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (your view)
      options:
        - Nice to have
        - Important
        - Critical / blocking
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I searched existing issues and didn’t find a duplicate.
          required: true
